### ISSUE TITLE
PDF417 detection

### ISSUE THREAD

**Issue by jeffreyliu8** [EzequielAdrianM/Camera2Vision#2]
I follow your example and try to apply the barcode pdf417 detection, it is not working as expected. The pdf417 barcode doesn't get detected very well(QR code works great, but not pdf417 format, i think it is due to threading issue...)

https://github.com/jeffreyliu8/camera2barcode

**Comment by EzequielAdrianM** [comment]
Sorry if you are having problems with the barcode detector. I have only tested this for Face Detection purposes. Do you have any link with more details about the mentioned "threading issue"?
