### ISSUE TITLE
ActivityMainBinding not found

### ISSUE THREAD

**Issue by yangshenys** [EzequielAdrianM/Camera2Vision#21]
The class com.randolabs.ezequiel.camera2.databinding.ActivityMainBinding is missing, the project can not build.

**Comment by EzequielAdrianM** [comment]
According to Android Studio Gradle docs, the binding file should auto generate. Here is a guide that may help: [https://medium.com/androiddevelopers/use-view-binding-to-replace-findviewbyid-c83942471fc](https://medium.com/androiddevelopers/use-view-binding-to-replace-findviewbyid-c83942471fc)

**Comment by yangshenys** [comment]
I updated my android-studio. This problem solved, thanks.
